/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Koru.glb --transform
Files: public/Koru.glb [354.16KB] > /workspace/Koru-transformed.glb [18.61KB] (95%)
*/

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useTexture } from '@react-three/drei'
import { AdditiveBlending, MathUtils, MeshStandardMaterial, SRGBColorSpace } from 'three'

const BREATH_CYCLE_SECONDS = 19
const HEAD_TILT_RADIANS = MathUtils.degToRad(15)
const BREATH_AMPLITUDE = 0.02
const SAFE_HARBOR_HOLD_MS = 3000
const CHEST_TARGET_POSITION = [0, 0.02, 0.56]
const CHEST_TARGET_SCALE = [1, 0.82, 0.32]
const CHEST_TARGET_RADIUS = 0.28
const CHEST_PULSE_RADIUS = 0.3
const EXTERNAL_TEXTURES = {
  baseColor: '/textures/koru-basecolor.png',
  roughness: '/textures/koru-roughness.png',
  normal: '/textures/koru-normal.png',
}

function getBreathPulse(phase) {
  if (phase < 4) {
    return Math.sin((phase / 4) * (Math.PI / 2))
  }

  if (phase < 11) {
    return 1
  }

  return Math.cos(((phase - 11) / 8) * (Math.PI / 2))
}

export function Koru({
  onSafeHarborActivate,
  safeHarborHoldMs = SAFE_HARBOR_HOLD_MS,
  ...props
}) {
  const { nodes, materials } = useGLTF('/Koru.glb')
  const bodyRef = useRef(null)
  const chestPulseRef = useRef(null)
  const chestPulseMaterialRef = useRef(null)
  const holdTimeoutRef = useRef(null)
  const interactionTarget = useRef(0)
  const baseBodyScale = useRef(null)
  const baseHeadRotation = useRef(null)
  const [isSafeHarborHolding, setIsSafeHarborHolding] = useState(false)
  const materialFallback = useMemo(() => Object.values(materials ?? {})[0] ?? null, [materials])
  const externalMaps = useTexture(EXTERNAL_TEXTURES)
  const meshNodes = useMemo(() => {
    return Object.values(nodes).filter((node) => node?.isMesh)
  }, [nodes])
  const meshDescriptors = useMemo(() => {
    return meshNodes.map((node) => ({
      key: node.uuid,
      name: node.name,
      geometry: node.geometry,
      position: node.position.toArray(),
      rotation: [node.rotation.x, node.rotation.y, node.rotation.z],
      scale: node.scale.toArray(),
    }))
  }, [meshNodes])

  const overrideMaterial = useMemo(() => {
    const sourceMaterial = materialFallback?.isMeshStandardMaterial
      ? materialFallback.clone()
      : new MeshStandardMaterial()

    sourceMaterial.name = 'KoruExternalTextureOverride'
    sourceMaterial.map = externalMaps.baseColor
    sourceMaterial.roughnessMap = externalMaps.roughness
    sourceMaterial.normalMap = externalMaps.normal
    sourceMaterial.map.colorSpace = SRGBColorSpace
    sourceMaterial.map.flipY = false
    sourceMaterial.roughnessMap.flipY = false
    sourceMaterial.normalMap.flipY = false
    sourceMaterial.normalScale.set(0.85, 0.85)
    sourceMaterial.roughness = 1
    sourceMaterial.metalness = 0.04
    sourceMaterial.needsUpdate = true

    return sourceMaterial
  }, [
    materialFallback,
    externalMaps.baseColor,
    externalMaps.roughness,
    externalMaps.normal,
  ])

  useEffect(() => {
    return () => {
      overrideMaterial.dispose()
    }
  }, [overrideMaterial])

  useEffect(() => {
    return () => {
      if (holdTimeoutRef.current) {
        window.clearTimeout(holdTimeoutRef.current)
      }
    }
  }, [])

  const headBone = useMemo(() => {
    const graphNodes = Object.values(nodes)
    const directBoneMatch = graphNodes.find((node) => {
      return node?.isBone && /head|neck|skull/i.test(node.name)
    })

    if (directBoneMatch) {
      return directBoneMatch
    }

    const skeletonBoneMatch = graphNodes
      .filter((node) => node?.isSkinnedMesh && node.skeleton?.bones?.length)
      .flatMap((node) => node.skeleton.bones)
      .find((bone) => /head|neck|skull/i.test(bone.name))

    return skeletonBoneMatch ?? null
  }, [nodes])

  useFrame(({ clock, pointer }, delta) => {
    const phase = clock.elapsedTime % BREATH_CYCLE_SECONDS
    const breathPulse = getBreathPulse(phase)
    const body = bodyRef.current

    if (body) {
      if (!baseBodyScale.current) {
        baseBodyScale.current = body.scale.clone()
      }
      const targetScale = 1 + breathPulse * BREATH_AMPLITUDE
      const easing = 1 - Math.exp(-4 * delta)
      body.scale.x = MathUtils.lerp(body.scale.x, baseBodyScale.current.x * targetScale, easing)
      body.scale.y = MathUtils.lerp(body.scale.y, baseBodyScale.current.y * targetScale, easing)
      body.scale.z = MathUtils.lerp(body.scale.z, baseBodyScale.current.z * targetScale, easing)
    }

    if (headBone) {
      if (!baseHeadRotation.current) {
        baseHeadRotation.current = {
          x: headBone.rotation.x,
          y: headBone.rotation.y,
        }
      }

      const targetYaw = MathUtils.clamp(pointer.x, -1, 1) * HEAD_TILT_RADIANS * interactionTarget.current
      const targetPitch =
        MathUtils.clamp(-pointer.y, -1, 1) * HEAD_TILT_RADIANS * 0.6 * interactionTarget.current
      const tiltEasing = 1 - Math.exp(-8 * delta)
      headBone.rotation.y = MathUtils.lerp(
        headBone.rotation.y,
        baseHeadRotation.current.y + targetYaw,
        tiltEasing,
      )
      headBone.rotation.x = MathUtils.lerp(
        headBone.rotation.x,
        baseHeadRotation.current.x + targetPitch,
        tiltEasing,
      )
    }

    const chestPulse = chestPulseRef.current
    const chestPulseMaterial = chestPulseMaterialRef.current

    if (chestPulse && chestPulseMaterial) {
      const pulseWave = 0.5 + Math.sin(clock.elapsedTime * Math.PI * 1.8) * 0.5
      const targetOpacity = isSafeHarborHolding ? 0.18 + pulseWave * 0.18 : 0
      const targetScale = isSafeHarborHolding ? 0.98 + pulseWave * 0.12 : 0.9
      const pulseEasing = 1 - Math.exp(-10 * delta)

      chestPulse.visible = isSafeHarborHolding || chestPulseMaterial.opacity > 0.01
      chestPulse.scale.x = MathUtils.lerp(chestPulse.scale.x, targetScale, pulseEasing)
      chestPulse.scale.y = MathUtils.lerp(chestPulse.scale.y, targetScale, pulseEasing)
      chestPulse.scale.z = MathUtils.lerp(chestPulse.scale.z, targetScale, pulseEasing)
      chestPulseMaterial.opacity = MathUtils.lerp(
        chestPulseMaterial.opacity,
        targetOpacity,
        pulseEasing,
      )
    }
  })

  const setInteracting = (value) => {
    interactionTarget.current = value
  }

  const cancelSafeHarborHold = useCallback(() => {
    if (holdTimeoutRef.current) {
      window.clearTimeout(holdTimeoutRef.current)
      holdTimeoutRef.current = null
    }

    setIsSafeHarborHolding(false)
  }, [])

  const startSafeHarborHold = useCallback(
    (event) => {
      event.stopPropagation()
      setInteracting(1)

      if (!onSafeHarborActivate || holdTimeoutRef.current) {
        return
      }

      event.target?.setPointerCapture?.(event.pointerId)
      setIsSafeHarborHolding(true)
      holdTimeoutRef.current = window.setTimeout(() => {
        holdTimeoutRef.current = null
        setIsSafeHarborHolding(false)
        onSafeHarborActivate()
      }, safeHarborHoldMs)
    },
    [onSafeHarborActivate, safeHarborHoldMs],
  )

  const stopSafeHarborHold = useCallback(
    (event) => {
      event?.stopPropagation()

      if (event?.target?.hasPointerCapture?.(event.pointerId)) {
        event.target.releasePointerCapture(event.pointerId)
      }

      cancelSafeHarborHold()
      setInteracting(0)
    },
    [cancelSafeHarborHold],
  )

  const ignoreRaycast = useCallback(() => null, [])

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerOut={() => setInteracting(0)}
      onPointerDown={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerUp={() => setInteracting(0)}
    >
      <group ref={bodyRef}>
        {meshDescriptors.map((mesh) => (
          <mesh
            key={mesh.key}
            name={mesh.name}
            geometry={mesh.geometry}
            position={mesh.position}
            rotation={mesh.rotation}
            scale={mesh.scale}
            material={overrideMaterial}
            castShadow
            receiveShadow
          />
        ))}
        <mesh
          position={CHEST_TARGET_POSITION}
          scale={CHEST_TARGET_SCALE}
          onPointerDown={startSafeHarborHold}
          onPointerUp={stopSafeHarborHold}
          onPointerOut={stopSafeHarborHold}
          onPointerCancel={stopSafeHarborHold}
          onLostPointerCapture={stopSafeHarborHold}
        >
          <sphereGeometry args={[CHEST_TARGET_RADIUS, 24, 16]} />
          <meshBasicMaterial transparent opacity={0} depthWrite={false} colorWrite={false} />
        </mesh>
        <mesh
          ref={chestPulseRef}
          position={CHEST_TARGET_POSITION}
          raycast={ignoreRaycast}
          visible={false}
        >
          <sphereGeometry args={[CHEST_PULSE_RADIUS, 32, 16]} />
          <meshBasicMaterial
            ref={chestPulseMaterialRef}
            color="#ffffff"
            transparent
            opacity={0}
            depthWrite={false}
            blending={AdditiveBlending}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Koru.glb')
useTexture.preload(EXTERNAL_TEXTURES)
