/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Koru.glb --transform
Files: public/Koru.glb [354.16KB] > /workspace/Koru-transformed.glb [18.61KB] (95%)
*/

import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { MathUtils } from 'three'

const BREATH_CYCLE_SECONDS = 19
const HEAD_TILT_RADIANS = MathUtils.degToRad(15)
const BREATH_AMPLITUDE = 0.02

function getBreathPulse(phase) {
  if (phase < 4) {
    return Math.sin((phase / 4) * (Math.PI / 2))
  }

  if (phase < 11) {
    return 1
  }

  return Math.cos(((phase - 11) / 8) * (Math.PI / 2))
}

export function Koru(props) {
  const { nodes, materials } = useGLTF('/Koru.glb')
  const bodyRef = useRef(null)
  const headPivotRef = useRef(null)
  const interactionTarget = useRef(0)
  const baseBodyScale = useRef(null)
  const materialFallback = useMemo(() => Object.values(materials ?? {})[0] ?? null, [materials])

  const headBone = useMemo(() => {
    return Object.values(nodes).find((node) => {
      return node.isBone && /head|skull|neck/i.test(node.name)
    })
  }, [nodes])

  useFrame(({ clock }, delta) => {
    const phase = clock.elapsedTime % BREATH_CYCLE_SECONDS
    const breathPulse = getBreathPulse(phase)
    const body = bodyRef.current

    if (body) {
      if (!baseBodyScale.current) {
        baseBodyScale.current = body.scale.clone()
      }
      const targetScale = 1 + breathPulse * BREATH_AMPLITUDE
      const easing = 1 - Math.exp(-4 * delta)
      body.scale.x = MathUtils.lerp(body.scale.x, baseBodyScale.current.x * targetScale, easing)
      body.scale.y = MathUtils.lerp(body.scale.y, baseBodyScale.current.y * targetScale, easing)
      body.scale.z = MathUtils.lerp(body.scale.z, baseBodyScale.current.z * targetScale, easing)
    }

    const tiltTarget = interactionTarget.current * HEAD_TILT_RADIANS
    const tiltNode = headBone || headPivotRef.current

    if (tiltNode) {
      const tiltEasing = 1 - Math.exp(-8 * delta)
      tiltNode.rotation.z = MathUtils.lerp(tiltNode.rotation.z, tiltTarget, tiltEasing)
    }
  })

  const setInteracting = (value) => {
    interactionTarget.current = value
  }

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerOut={() => setInteracting(0)}
      onPointerDown={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerUp={() => setInteracting(0)}
    >
      <group ref={headPivotRef}>
        <mesh
          ref={bodyRef}
          geometry={nodes.Mesh10.geometry}
          material={nodes.Mesh10.material ?? materialFallback}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Koru.glb')
