/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Koru.glb --transform
Files: public/Koru.glb [354.16KB] > /workspace/Koru-transformed.glb [18.61KB] (95%)
*/

import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { MathUtils } from 'three'

const BREATH_CYCLE_SECONDS = 19
const HEAD_TILT_RADIANS = MathUtils.degToRad(15)

function getBreathLift(phase) {
  if (phase < 4) {
    return MathUtils.smoothstep(phase / 4, 0, 1)
  }

  if (phase < 11) {
    return 1
  }

  return 1 - MathUtils.smoothstep((phase - 11) / 8, 0, 1)
}

export function Koru(props) {
  const { nodes } = useGLTF('/Koru-transformed.glb')
  const bodyRef = useRef(null)
  const headPivotRef = useRef(null)
  const interactionTarget = useRef(0)

  const headBone = useMemo(() => {
    return Object.values(nodes).find((node) => {
      return node.isBone && /head|skull|neck/i.test(node.name)
    })
  }, [nodes])

  useFrame(({ clock }, delta) => {
    const phase = clock.elapsedTime % BREATH_CYCLE_SECONDS
    const breathLift = getBreathLift(phase)
    const body = bodyRef.current

    if (body) {
      body.scale.y = MathUtils.lerp(body.scale.y, 1 + breathLift * 0.055, 0.08)
    }

    const tiltTarget = interactionTarget.current * HEAD_TILT_RADIANS
    const tiltNode = headBone || headPivotRef.current

    if (tiltNode) {
      tiltNode.rotation.z = MathUtils.damp(tiltNode.rotation.z, tiltTarget, 5, delta)
    }
  })

  const setInteracting = (value) => {
    interactionTarget.current = value
  }

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerOut={() => setInteracting(0)}
      onPointerDown={(event) => {
        event.stopPropagation()
        setInteracting(1)
      }}
      onPointerUp={() => setInteracting(0)}
    >
      <group ref={headPivotRef}>
        <mesh
          ref={bodyRef}
          geometry={nodes.Mesh10.geometry}
          material={nodes.Mesh10.material}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Koru-transformed.glb')
